service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30 
  httpApi: 
    cors: true
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - httpApi:
          method: GET
          path: /api/get-auth-url
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - httpApi:
          method: GET
          path: /api/token
  getCalenderEvents:
    handler: handler.getCalenderEvents
    events: 
      - httpApi: 
          method: GET
          path: /api/get-events/{access_token}

